using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BuildingMaintenance.CommonCode.Helpers
{
    public class TableDetailed
    {
        public string TableName { get; set; }
        public short Rows { get; set; } = 1;
        public List<TableOtherColumns> TableOtherColumns { get; set; }
        public short DisplaySeqNo { get; set; }
        public bool IsNewRecord { get; set; }
        public string DeletedColumnName { get; set; }
        public TableRowBeforeDelete TableRowBeforeDelete { get; set; }
        public TableExistingRecordDelete TableExistingRecordDelete { get; set; }

    }

    public class TableRowDetailed
    {
        public string ColumnName { get; set; }
        public bool IsPrimaryKey { get; set; } = false;
        public bool IsAutoGenerated { get; set; } = false;
        public string Type { get; set; } = string.Empty;
        public object Value { get; set; }
        public bool IsStringColumn { get; set; } = true;
        public bool IsNewRecord { get; set; } = true;
        public short ActionType { get; set; }
        public string FormKeyName { get; set; } = string.Empty;
    }

    public class TableOtherColumns
    {
        public string Column { get; set; }
        public short Rows { get; set; } = 1;
        public bool IsRequired { get; set; }
    }

    public class TableRowBeforeDelete
    {
        public string Table { get; set; }
        public string Column { get; set; }
    }

    public class TableExistingRecordDelete
    {
        public bool IsExistingRecordDelete { get; set; } = false;
        public string Column { get; set; }
    }
}
